### ISSUE TITLE
Using Android default file manager

### ISSUE THREAD

**Issue by DevNaNuvem** [39aldo39/DecSync#11]
Hello and thank you very much for this awesome APP.

Is it possible to change the file manager to use android's default?

This way it would be possible to store the calendar/contacts inside of veracrypt containers mounted on the system, improving a lot the security.

**Comment by 39aldo39** [comment]
It would be nice to use the default file manager. However, it returns an abstract file which is currently not supported. But I am also working on support for encryption, which would mean that you don't need a container.

**Comment by 39aldo39** [comment]
It is supported in the next version, using the Storage Access Framework!
