### ISSUE TITLE
Trouble using SD card

### ISSUE THREAD

**Issue by JohnVeness** [39aldo39/DecSync#14]
Many thanks for this app.

By default, at least on my phone, it uses /storage/emulated/0/DecSync, which is stored on the phone built-in memory. I wanted to change it to store on microSD instead, which on my phone appears as /storage/1443-10E3

First problem (apologies if putting multiple problems in one issue is undesired. I can split if required, but wasn't sure whether they might be linked):

I could browse to /storage/1443-10E3 within DecSync CC settings OK, but if I tried to create a folder within there using the top-right button I get an error: "Failed to create folder".

No problem I thought, I'll create a folder using a file manager, then browse to that folder in DecSync CC, which seemed to work.

However, now if I try to create a Calendar or Contacts collection, the app will crash: "DecSync CC has stopped", with a Restart app button. Looking in the folder in a file manager, nothing has been created.

Third problem: I thought "Oh well, seems like the app doesn't want to work with microSD, I'll change it back to default", but in DecSync CC settings I cannot change the folder back to /storage/emulated/0/DecSync. Specifically, I can browse to /storage/emulated but there is no "0" folder in there.

I managed to get round the last problem by deleting the apps settings in Android Settings, Apps, and the app seems to work OK using the internal storage - I can create calendar and contact collections with no errors for example. But still the problem remains of not being able to use microSD.

My phone is a Sony Xperia Z5 Compact running Android 7.1.1.

Many thanks again for this app.

**Comment by 39aldo39** [comment]
Using the SD card indeed leads to problems (see also 39aldo39/DecSyncCC#11). But not being able to change the DecSync directory back is very bad. I think I will add an extra button to reset the DecSync directory. Luckily the data is stored on the file system, so it is not lost when you delete the app settings.

**Comment by JohnVeness** [comment]
Thanks.

By the way, I didn't realise this had already been reported as an issue, but I now see it in the DecSyncCC repo. I used Settings, About DecSync to get to this repo. Maybe the Settings link should go to DecSyncCC repo instead?

**Comment by 39aldo39** [comment]
I have changed the Settings link to go to DecSync CC. It is indeed more logical to go the repo of the app. In spaRSS DecSync there is still a link to this repo, as one might wonder what 'DecSync synchronization' is.
