### ISSUE TITLE
App crashes with no helpful message if DecSync folder exists before installing

### ISSUE THREAD

**Issue by JacobRoth** [39aldo39/DecSync#15]
I got a new Android device with LineageOS 16 with MicroG. I set up SyncThing and synced my folders first. This of course included the DecSync folder. 

Then I installed DecSync for Android, but every time I tried to open it it crashed immediately. I did `adb logcat` to figure out what was going on and saw that the error was:

`AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.decsync.cc/org.decsync.cc.MainActivity}: java.io.FileNotFoundException: /storage/emulated/0/DecSync/.decsync-info (Permission denied)`

oh, so I hadn't given it storage access permissions yet. I went into the Android settings and gave it those, and it works now. Easy fix, but it was very unclear what the problem was and without my computer and adb I wouldn't have figured it out.

DecSync should probably check for those permissions before crashing like this.

**Comment by gaeoh** [comment]
I can confirm the issue, and also that the fix is working.

Also LineageOS 16 with MicroG. However, I did NOT set up syncthing first, so the folder did not exist for me.

**Comment by 39aldo39** [comment]
Thanks for the report!

The app actually checks for the permissions, but recently there was some code wrongly added before those checks. But such crashes are indeed bad.
