### ISSUE TITLE
Add DecSync to privacytools.io

### ISSUE THREAD

**Issue by moritztk** [39aldo39/DecSync#16]
Hi @39aldo39 
I really really enjoy DecSync and I think there are great privacy advantages over any other solution to sync calendar and contacts.

To gain more traction, it might be worse investing time in present the project to privacytools.io, they are certainly open to it: https://github.com/privacytoolsIO/privacytools.io/issues/1416

**Comment by 39aldo39** [comment]
Thanks for letting me know. I think you presented DecSync very well! I will close this issue as the linked one is the relevant one.
