### ISSUE TITLE
[Request] Make it possible to sync standard .ics and .vcf files

### ISSUE THREAD

**Issue by jones137** [39aldo39/DecSync#17]
I need DecSync only for automated calendar/contacts backup, not necessarily for synchronization to another app. But due to DecSync's format I have to manually concatenate specific files to have a usable .ics or .vcf file ready to import somewhere. So, I would be grateful if you allowed to also keep standardized, whole .ics and .vcf files in sync directory in addition to only single-entry folder tree.

**Comment by 39aldo39** [comment]
This falls outside the scope of DecSync, as it is meant to be synchronized. Aren't there other apps that can create backups? I know that some let you export, but not automatically.
