### ISSUE TITLE
Allow for directory merging in app

### ISSUE THREAD

**Issue by GBT7** [39aldo39/DecSync#18]
With a recent update, DecSync appears to have stopped using the directory I've saved all of my stuff to, even though I selected the directory for it to use when it asked. I've added events since then without noticing the issue, and now I'm stuck with trying to juggle those events between either import-exports from calendar apps, or offline calendars so that I can change the directory and move them all back to my actual DecSync folder again. It's a pain in the arse, and I just want to merge folders, but I don't know if just copy-pasting them together will break anything or not.

**Comment by 39aldo39** [comment]
The situation is a bit unfortunate, as an update I did that required you to re-select the DecSync directory did not go well, so I had to revert it. This also meant that the previous stored location didn't get remembered...

I understand that it is frustrating, but the simplest solution for now is the following:
- Install [Calendar Import -Export](https://f-droid.org/en/packages/org.sufficientlysecure.ical/)
- Select the 'wrong' DecSync directory with just a few events
- Export the calendar to an ics file with Calendar Import-Export
- Select the 'right' DecSync directory
- Import the ics file to the right collection

**Comment by kocjs** [comment]
The latest version 1.2.2 does reverts the decsync directry back to the default /DecSync.

Steps to reproduce

Install the app, change the sync directory to suit your needs. Create a new address book it creates the directory structure in the right place. Add the first contact and it's entries are created in the default directory.

**Comment by 39aldo39** [comment]
For me it works fine. If I change the DecSync directory, the first contact is also created in the right place. It would be very strange if it would use two different directories. What is your Android version?
