### ISSUE TITLE
"Read" status not synced

### ISSUE THREAD

**Issue by kuba-orlik** [39aldo39/DecSync#23]
I'm using SpaRSS DecSync together with FeedReader, connected to the same DecSync folder.

When I mark certain item as read in FeedReader, the same item is still marked as unread in SpaRSS, even after refreshing multiple times.

Is this functionality not implemented, or I misconfigured something?

**Comment by 39aldo39** [comment]
It should definitely work. Did synchronizing the subscriptions work? If possible, could share the feed you tried?

**Comment by kuba-orlik** [comment]
It seems that it has synced eventually. I'll reopen this issue if I'll mange to catch it red-handed again. Thanks for checking in!
