### ISSUE TITLE
Independent bridge

### ISSUE THREAD

**Issue by julianfairfax** [39aldo39/DecSync#35]
First off, thanks for creating this amazing way to sync contacts and calendars all locally. It's very convenient to be able to do that, but it could be improved. Currently your only option for using DecSync across all desktop platforms is by using a Radicale plugin. This is not a good user experience since you have to use a third-party piece of software to get your contacts and calendars syncing. It would be nice if DecSync had an independent bridge for desktop either inspired by or forked from EteSync, that would run in the background and simply output CalDAV and CardDAV URLs to use in your apps. I mentioned EteSync since they also had a similar approach with a Radicale plugin and then decided to create their own little application instead. Something along the lines of this would be more user friendly and provide a better experience for DecSync as whole. Thanks for your work on this project and I hope it continues to improve!

**Comment by julianfairfax** [comment]
Feel free to close or leave this open as you like but the Radicale web interface is actually only needed just to create a collection and then never again so it's really not important.

**Comment by julianfairfax** [comment]
Closed since the Radicale web interface isn't actually needed at all for using DecSync itself

**Comment by julianfairfax** [comment]
Close this if you don't agree or don't think it's worth it, but it'd be nice to be a more independent product!

**Comment by alensiljak** [comment]
While I agree that it would be nice to have something more convenient (since I've had some issues with the data being corrupted and parts of SQLite database being spewn into the contact files) but isn't Radicale already a "more independent product"? It is a specialized tool exactly for the purpose of serving data via CalDAV and CardDAV. DecSync provides a plugin which bridges the DecSync storage with the Cal/Card DAV interface that Radicale provides.
Radicale is implemented in Python, making it possible to run in Termux on Android devices, besides all the desktop OS's.

What exactly would be the benefit of having a (redundant) application that does exactly the same thing? Isn't it just introducing another tool to maintain?

I mean, I like your idea. But, thinking logically, I simply cannot find any arguments to support it, unfortunately.

**Comment by julianfairfax** [comment]
Convenience

**Comment by alensiljak** [comment]
Would you mind to elaborate?

**Comment by julianfairfax** [comment]
Installing one app with it's own icon to launch it is easier than installing a server, a plugin, configuring the server, starting the server, and then visiting it in a browser.

**Comment by alensiljak** [comment]
Are you saying that running pip twice and creating a minor config file is inconvenient? You don't have to open the browser. The server will await connections from the clients whether you look at it or not. Or am I missing something?

You *have to* configure the gui app, too. It's not just plug and play.
Also, speaking of icons - which environment / operating system are we talking about here?
The current solution will run on Linux, Windows, and Android. Which gui will allow the same?

Can we also mention the convenience for the maintainer(s)? I see two contributors on the project. Do you know how much effort is to maintain even one gui app, with constantly evolving platforms, sdks, dependencies, etc.?

**Comment by julianfairfax** [comment]
> Are you saying that running pip twice and creating a minor config file is inconvenient?

It is
> You don't have to open the browser. The server will await connections from the clients whether you look at it or not. Or am I missing something?
> 

If you actually want to use the interface you do
> You _have to_ configure the gui app, too. It's not just plug and play. 

It is: https://github.com/etesync/etesync-dav#installation
> Also, speaking of icons - which environment / operating system are we talking about here? The current solution will run on Linux, Windows, and Android. Which gui will allow the same?
> 

This one: https://github.com/etesync/etesync-dav
> Can we also mention the convenience for the maintainer(s)? I see two contributors on the project. 

How about the maintainer comment on that.

> Do you know how much effort is to maintain even one gui app, with constantly evolving platforms, sdks, dependencies, etc.?

Considering a solution like https://github.com/etesync/etesync-dav is just built on top of Radicale but better integrated, not much.

**Comment by alensiljak** [comment]
Seems like you already have a solution!

**Comment by julianfairfax** [comment]
And what exactly is that then?

**Comment by julianfairfax** [comment]
Closing this since EteSync's solution is basically the exact same thing just better suited for their needs.
