### ISSUE TITLE
How to completely remove sync nodes? 

### ISSUE THREAD

**Issue by alensiljak** [39aldo39/DecSync#40]
What is the preferred way to completely remove the traces of a sync node?

Use case: I sometimes create Radicale nodes for desktop. At some point, I'd like to completely remove any references to these nodes from the data files.

So far I've done that manually. Not sure if the stale records, from the nodes which no longer sync, may cause any issues in the future, in case the names are duplicate or something like that.

**Comment by 39aldo39** [comment]
You can remove nodes by selecting the `Manage DecSync data` option for a collection in DecSync CC. As for the stale records, those shouldn't cause any problem.

**Comment by alensiljak** [comment]
Thanks!
I had set up Radicale several times while I was cleaning up the contacts and calendar records and needed to start over.
At some point, I just created a copy of the data storage instead of syncing. That helped to reduce the workload on cleaning up.
