### ISSUE TITLE
Please add feature to import contact and calendars

### ISSUE THREAD

**Issue by qwertyuser1983** [39aldo39/DecSync#6]
Adding my 10000++ contact to the app one by one is impossible. 

If there a way to import contact / calendar from text / vcard / vcf files or from mobile / google contact is highly appreciated.

(´ ∀ ` *) 

Renan

**Comment by 39aldo39** [comment]
It is possible to import contacts/calendars from vcf/ics files! On Android you can use the default contacts app (Settings → Import), and  [Calendar Import-Export](https://f-droid.org/app/org.sufficientlysecure.ical). On Evolution, you can open a vcf/ical file and open it in Evolution to import it.

**Comment by qwertyuser1983** [comment]
Aah, ok. Too bad for me that I am using KDE. Will wait then. (｡•́︿•̀｡)

**Comment by 39aldo39** [comment]
You can still import contacts on Android, right?

**Comment by qwertyuser1983** [comment]
> You can still import contacts on Android, right?

Sorry for late reply. 

The decsync link did not exist in contact menu, but that may because I have Davdroid / Davx^5 installed.

**Comment by 39aldo39** [comment]
Davx⁵ should not matter. But you have to enable a collection before you can import into it. Maybe that's it?

**Comment by qwertyuser1983** [comment]
> Davx⁵ should not matter. But you have to enable a collection before you can import into it. Maybe that's it?

[after Face palms and self inflicting curses]

Yups, definitely it. It solves the problem. 

Thanks! :)
